### ISSUE TITLE
Crypto or Cryptodome

### ISSUE THREAD

**Issue by KvEijden** [UtrechtUniversity/remindo-api#4]
>>> from remindo_api import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/keesvaneijden/RSE/remindo-api/src/remindo_api/client.py", line 13, in <module>
    from .request import RemindoRequest
  File "/Users/keesvaneijden/RSE/remindo-api/src/remindo_api/request.py", line 7, in <module>
    from Crypto.Hash import HMAC, SHA256, SHA1
ModuleNotFoundError: No module named 'Crypto'
>>> 
Shouldn't the module name be Cryptodome instead of Crypto?

**Comment by leonardovida** [comment]
I understood the error. You installed from "requirements" right? Those were not updated with the last version of pycryptodome. Can you try installing the last version?

In response to your answer; `Crypto` is correct as from the last release of pycryptodome (https://pycryptodome.readthedocs.io/en/latest/src/introduction.html) the import is `Crypto.XXX`.

**Comment by leonardovida** [comment]
@KvEijden if you pull the last commit and do the usual ` pip install -r requirements.txt` it should now work.
